apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
  namespace: abdul-dicoding-namespace
  labels:
    app: karsajobs
spec:
  selector:
    app: karsajobs
  ports:
    - port: 8000
  type: NodePort
