apiVersion: v1
kind: Service
metadata:
  name: karsajobs-backend
  namespace: abdul-dicoding-namespace
  labels:
    app: karsajobs
spec:
  selector:
    type: backend
  ports:
    - port: 8080
  type: NodePort