apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: abdul-dicoding-namespace
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
