apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: abdul-dicoding-namespace
  labels:
    app: mongo-service
spec:
  selector:
    type: db
  ports:
    - port: 27017
  clusterIP: None
